version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: newsapp-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: newsappdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: newsapp-redis
    ports:
      - "6379:6379"


volumes:
  postgres-data:
